### ISSUE TITLE
Date picker does not show up

### ISSUE THREAD

**Issue by morreau** [bamadesigner/conference-schedule#1]
Hey Rachel, really like the idea of this conference plugin... but can not get it to work fully.
I installed this plugin + "WP REST API Version 2.0-beta15" on  WP 4.6
The date picker does not show up, and can not select any categories...
Is there something i'm missing?

Thank so much for any insights.

![screen shot 2016-10-11 at 20 06 41](https://cloud.githubusercontent.com/assets/2155726/19282348/4e9a04b6-8fee-11e6-8b04-252eeaef7598.png)

**Comment by mackensen** [comment]
I saw this as well. The plugin doesn't ship with minified CSS so you have to install the development tools and compile the CSS at least once for the datepicker to work.

**Comment by bamadesigner** [comment]
Hmm... yea. I'm used to these plugins being in the repo and therefore I move compiled assets over to SVN. I will remove the compiled assets from being ignored as to remove this issue. Thanks!
