### ISSUE TITLE
REST API Doesn't Allow -1 Posts Per Page

### ISSUE THREAD

**Issue by cgrymala** [bamadesigner/conference-schedule#4]
The REST API limits posts_per_page to 100, so you can't set that parameter to -1 like you can with a traditional post query. If you do set it to -1, then the API returns a WP_Error indicating that the page number is invalid.

To fix this, I updated Line 386 of conference-schedule.php to set the parameter to 100 instead of -1. This is a short-term fix, though, as any usage that includes more than 100 "events" will need to implement paging in some way.

**Comment by bamadesigner** [comment]
Fixed with https://github.com/bamadesigner/conference-schedule/commit/979c8f8891ca175d8c0d4eb923a12e296a9d6fc3
